---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: defn/python
  commands:
  - . /drone/venv/bin/activate && pytest -v --cov=main --cov-report=term-missing src

---
kind: pipeline
type: docker
name: fmt

platform:
  os: linux
  arch: amd64

steps:
- name: python
  image: defn/python
  commands:
  - . /drone/venv/bin/activate && isort -rc src
  - . /drone/venv/bin/activate && black src

- name: drone
  image: defn/container
  commands:
  - drone fmt --save

---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: defn/python
  commands:
  - . /drone/venv/bin/activate && pyflakes src
  - . /drone/venv/bin/activate && mypy src

---
kind: pipeline
type: docker
name: validate

platform:
  os: linux
  arch: amd64

steps:
- name: drone
  image: defn/container
  commands:
  - drone lint

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: defn/container
  commands:
  - cp config.yaml.template config.yaml
  - hugo
  - rm -f config.yaml

- name: gh-pages
  image: defn/container
  commands:
  - "(cat config.yaml.template; echo; echo uglyurls: false; echo publishDir: gh-pages) > config.yaml"
  - hugo
  - rm -f config.yaml

---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: defn/drone-kaniko
  settings:
    cache: true
    password:
      from_secret: docker_password
    repo: defn/python
    skip_tls_verify: true
    tags: latest
    username:
      from_secret: docker_username

...
