---
kind: pipeline
type: docker
name: style

platform:
  os: linux
  arch: amd64

steps:
- name: fmt
  image: letfn/drone
  settings:
    task: fmt

- name: lint
  image: letfn/drone
  settings:
    task: lint

---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/python
  commands:
    - cd
    - . /app/venv/bin/activate
    - test "/app/venv/bin/python" = "$(which python)"
    - test "/app/venv/bin/pip" = "$(which pip)"
    - echo "$TEST_PY" | base64 -d > test.py
    - pytest -v test.py

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo

---
kind: pipeline
type: docker
name: requirements

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/python
  commands:
  - . /app/venv/bin/activate
  - pip-compile /drone/src/requirements.in -o /tmp/requirements.txt
  - if test -w . ; then cp /tmp/requirements.txt requirements.txt; else diff requirements.txt /tmp/requirements.txt || true;  fi

...
