---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/drone-kaniko
  settings:
    cache: true
    cache_repo: letfn/cache
    dockerfile: alt/Dockerfile
    password:
      from_secret: docker_password
    repo: letfn/python
    skip_tls_verify: true
    tag: latest
    username:
      from_secret: docker_username

---
kind: pipeline
type: docker
name: fmt

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - drone fmt --save

---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - drone lint

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo

- name: gh-pages
  image: letfn/drone-hugo
  settings:
    github_pages: true

---
kind: pipeline
type: docker
name: fmt-python

platform:
  os: linux
  arch: amd64

steps:
- name: python
  image: letfn/python
  commands:
  - . /drone/venv/bin/activate && isort -rc src
  - . /drone/venv/bin/activate && black src

---
kind: pipeline
type: docker
name: lint-python

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/container
  commands:
  - . /drone/venv/bin/activate && pyflakes src
  - . /drone/venv/bin/activate && mypy src

---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/python
  commands:
  - . /drone/venv/bin/activate && pytest -v --cov=main --cov-report=term-missing src

...
