---
kind: pipeline
type: docker
name: style

platform:
  os: linux
  arch: amd64

steps:
- name: drone fmt
  image: letfn/drone
  settings:
    task: fmt

- name: drone lint
  image: letfn/drone
  settings:
    task: lint

---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: letfn/python
  image: letfn/python
  commands:
    - cd
    - . /app/venv/bin/activate
    - test "/app/venv/bin/python" = "$(which python)"
    - test "/app/venv/bin/pip" = "$(which pip)"
    - test "Python 3.8.5" = "$(python --version)"
    - test "boot" = "$(whoami)"
    - pip install python-dotenv
    - echo "$TEST_PY" | base64 -d > test.py
    - pytest -v test.py

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo

---
kind: pipeline
type: docker
name: requirements

platform:
  os: linux
  arch: amd64

steps:
- name: everything
  image: letfn/python
  commands:
  - . /app/venv/bin/activate
  - pip-compile /drone/src/requirements.in -o /tmp/requirements.txt
  - diff requirements.txt /tmp/requirements.txt || true
  - if test -w . ; then cp /tmp/requirements.txt requirements.txt; fi

...
