version: '3.7'

services:
  docs:
    image: letfn/drone-hugo
    volumes:
      - ".:/app/src"
    ports:
      - 1313
    environment:
      - PLUGIN_WATCH=yes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.whoa.bot`)"

networks:
  default:
    external:
      name: kitt
