version: 2.1
commands:
  install_drone:
    steps:
      - run:
          name: Install Drone
          command: |
            curl -sSL -O https://github.com/drone/drone-cli/releases/download/v1.2.1/drone_linux_amd64.tar.gz
            tar xvfz drone_linux_amd64.tar.gz drone
            rm -f drone_linux_amd64.tar.gz
            chmod 755 drone
            sudo mv drone /usr/local/bin/
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - install_drone
      - checkout
      - run: make ci-base
      - run: make all
      - run: make docs

workflows:
  version: 2
  aws-okta:
    jobs:
      - build
